version: "3"
volumes:
  esagonario-datasets:
    external: true
networks:
  reverse-proxy:
    external: true
services:
  backend:
    build:
      context: ./..
      dockerfile: docker/backend.dockerfile
    container_name: esagonario-backend
    restart: unless-stopped
    volumes:
      - esagonario-datasets:/datasets
    networks:
      - reverse-proxy
  frontend:
    build:
      context: ./..
      dockerfile: docker/frontend.dockerfile
    container_name: esagonario-frontend
    hostname: esagonario
    restart: unless-stopped
    networks:
      - reverse-proxy
    depends_on:
      - backend
